### ISSUE TITLE
how did you make npy data?

### ISSUE THREAD

**Issue by lz666win** [rmsouza01/Hybrid-CS-Model-MRI#1]
I want to appear again your work with my own data,did you use complex k space data or abs image data's ifft result?

**Comment by rmsouza01** [comment]
Hello,

I am not sure I understand the question. The npy data was created from raw-data acquired on a GE scanner using Orchestra Toolbox. Between the k-space u-net and the image domain u-net I take the absolute of the iFFT. Later on, I realized that the method works better without the absolute operation.

**Comment by lz666win** [comment]
sorry to bother you again ,for the code frequency_spatial_network.py,the function wnet_dc has a line:
conv8_dc = Lambda(lambda conv8 : conv8*mask)(conv8)
res1 = Add()([conv8_dc,inputs])
I think this line is data consistency (DC) blocks,but when I check the orignal paper,I think this layer is  keeping the sampled k-space,and update the unsampled k-space,so I think this line should be written like:
conv8_dc = Lambda(lambda conv8 : conv8*(1-mask))(conv8)
res1 = Add()([conv8_dc,inputs])
that is my point.

**Comment by rmsouza01** [comment]
Mask in my code represents positions that were not sampled. If it represented sampled positions, then, your suggestion would be correct.
